parameters:
#    hammond_church.example.class: Hammond\ChurchBundle\Example

services:
#    hammond_church.example:
#        class: %hammond_church.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
