Hammond\ChurchBundle\Entity\ChurchImages:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255

    manyToOne:
        church:
            targetEntity: Church
            inversedBy: images

    lifecycleCallbacks: {  }
